name: reverb
description: "Your music. Slowed down."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.6.0
  slang_flutter: ^4.2.0
  slang: ^4.2.1
  get_it: ^8.0.2
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  hydrated_bloc: ^9.1.5
  adaptive_theme: ^3.6.0
  path_provider: ^2.1.5
  just_audio: ^0.9.42
  on_audio_query_forked: ^2.9.1
  meta: ^1.15.0
  video_player: ^2.9.2
  form_builder_validators: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Silkscreen
      fonts:
        - asset: fonts/Silkscreen-Bold.ttf
          weight: 700
        - asset: fonts/Silkscreen-Regular.ttf
          weight: 400
    - family: BrunoAceSC
      fonts:
        - asset: fonts/BrunoAceSC-Regular.ttf
          weight: 400
    - family: Raleway
      fonts:
        - asset: fonts/raleway-static/Raleway-Regular.ttf
          weight: 100
        - asset: fonts/raleway-static/Raleway-Medium.ttf
          weight: 200
        - asset: fonts/raleway-static/Raleway-Bold.ttf
          weight: 600
        - asset: fonts/raleway-static/Raleway-Black.ttf
          weight: 900
        - asset: fonts/raleway-static/Raleway-MediumItalic.ttf
          style: italic


